services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brasilia-racing-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
      - /app/node_modules
